### ISSUE TITLE
Can't download for some reason

### ISSUE THREAD

**Issue by SobshLPB** [Solar-Tweaks/LunarSocket#21] opened 2022-05-25 22:16 UTC
src/commands/CommandHandler.ts:4:18 - error TS2307: Cannot find module './deop' or its corresponding type declarations.

4 import deop from './deop';
                   ~~~~~~~~

src/commands/CommandHandler.ts:7:16 - error TS2307: Cannot find module './op' or its corresponding type declarations.

7 import op from './op';

Found 2 errors in the same file, starting at: src/commands/CommandHandler.ts:4

https://i.imgur.com/Op7ExjP.png

**Comment by RichardDorian** [comment] 2022-06-14 08:49
Make sure to run `git pull` and `npm install` before trying to build the app. Closing since the issue is kinda old, feel free to re open it if you need to.

**Closed by RichardDorian** 2022-06-14 08:49 UTC
